/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Message;
import javax.mail.Transport;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import services.UtilisateurService;

/**
 *
 * @author adhmin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("Authentification");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bnConnexion = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        bnMtpOublier = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPassword.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setText("Login:");

        jLabel2.setText("Mot de passe:");

        bnConnexion.setText("Connexion");
        bnConnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnConnexionMouseClicked(evt);
            }
        });
        bnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnConnexionActionPerformed(evt);
            }
        });

        bnMtpOublier.setText("Mot de passe oublier");
        bnMtpOublier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnMtpOublierActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\adhmin\\Documents\\NetBeansProjects\\gestion_examens\\src\\images\\link.png")); // NOI18N

        javax.swing.GroupLayout txtPasswordLayout = new javax.swing.GroupLayout(txtPassword);
        txtPassword.setLayout(txtPasswordLayout);
        txtPasswordLayout.setHorizontalGroup(
            txtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPasswordLayout.createSequentialGroup()
                .addGroup(txtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(txtPasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtPasswordLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(bnConnexion))
                    .addGroup(txtPasswordLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(bnMtpOublier))
                    .addGroup(txtPasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLogin)))
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        txtPasswordLayout.setVerticalGroup(
            txtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtPasswordLayout.createSequentialGroup()
                .addGroup(txtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtPasswordLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(txtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(txtPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(bnConnexion)
                        .addGap(64, 64, 64)
                        .addComponent(bnMtpOublier))
                    .addGroup(txtPasswordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnConnexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnConnexionActionPerformed

    private void bnConnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnConnexionMouseClicked
        // TODO add your handling code here:
        String login = txtLogin.getText().toString();
        String password = txtpassword.getText().toString();
        if (password.equals("1234") && login.equals("ens")) {
            MDIApplication mdi = new MDIApplication();
            mdi.setVisible(true);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "Login ou mot de passe incorrect");
        }
    }//GEN-LAST:event_bnConnexionMouseClicked

    private void bnMtpOublierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnMtpOublierActionPerformed

        String login = txtLogin.getText().trim();
        UtilisateurService utilisateurService = new UtilisateurService();

        if (!utilisateurService.checkUtilisateurExists(login)) {
            JOptionPane.showMessageDialog(this, "L'utilisateur est inconnu.");
            return;
        }

        String email = demanderEmail();
        if (email == null || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "L'adresse email ne peut pas être vide.");
            return;
        }

        String reponseSecrete = demanderReponseSecrete();
        if (reponseSecrete == null || !reponseSecrete.trim().equalsIgnoreCase("chat")) {
            JOptionPane.showMessageDialog(this, "Réponse incorrecte à la question secrète.");
            return;
        }

        String nouveauMotDePasse = demanderNouveauMotDePasse();
        if (nouveauMotDePasse == null || nouveauMotDePasse.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le mot de passe ne peut pas être vide.");
            return;
        }

        boolean result = utilisateurService.changerMotDePasse(login, nouveauMotDePasse);
        if (result) {
            envoyerEmail(nouveauMotDePasse, email);
            JOptionPane.showMessageDialog(this, "Mot de passe changé avec succès !");
        } else {
            JOptionPane.showMessageDialog(this, "Échec du changement de mot de passe.");
        }
    }

    private String demanderEmail() {
        return JOptionPane.showInputDialog(this, "Entrez votre adresse email");
    }

    private String demanderReponseSecrete() {
        return JOptionPane.showInputDialog(this, "Quelle est votre animal prefere ?");
    }

    private String demanderNouveauMotDePasse() {
        return JOptionPane.showInputDialog(this, "Entrez votre nouveau mot de passe");
    }

    private void envoyerEmail(String nouveauMotDePasse, String email) {
        Properties properties = new Properties();
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.auth", "true");

        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("moustinehalima5@gmail.com", "");
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("moustinehalima5@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
            message.setSubject("Récupération de mot de passe");
            String messageContent = "Bonjour,\n\nVotre nouveau mot de passe est : " + nouveauMotDePasse + "\n\nCordialement,";
            message.setText(messageContent);

            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Votre nouveau mot de passe a été envoyé à votre adresse email.");
        } catch (MessagingException e) {
            JOptionPane.showMessageDialog(this, "Échec de l'envoi du mot de passe. Vérifiez l'adresse email.");
        }

    }//GEN-LAST:event_bnMtpOublierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnConnexion;
    private javax.swing.JToggleButton bnMtpOublier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPanel txtPassword;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
