/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author adhmin
 */
public class MDIApplication extends javax.swing.JFrame {

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des examens");
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        etudiantMenuEtudiant = new javax.swing.JMenuItem();
        ExamenMenuItem = new javax.swing.JMenuItem();
        InscriptionMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        ExamenParMatiereMenuItem = new javax.swing.JMenuItem();
        EtudiantParExamenMenuItem1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 255, 255));

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        etudiantMenuEtudiant.setMnemonic('o');
        etudiantMenuEtudiant.setText("Etudiant");
        etudiantMenuEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantMenuEtudiantActionPerformed(evt);
            }
        });
        fileMenu.add(etudiantMenuEtudiant);

        ExamenMenuItem.setMnemonic('s');
        ExamenMenuItem.setText("Examen");
        ExamenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamenMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ExamenMenuItem);

        InscriptionMenuItem.setMnemonic('x');
        InscriptionMenuItem.setText("Inscription Examen");
        InscriptionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscriptionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(InscriptionMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Filtrer");

        ExamenParMatiereMenuItem.setMnemonic('t');
        ExamenParMatiereMenuItem.setText("ExamenParMatiere");
        ExamenParMatiereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamenParMatiereMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(ExamenParMatiereMenuItem);

        EtudiantParExamenMenuItem1.setText("EtudiantParExamen");
        EtudiantParExamenMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantParExamenMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(EtudiantParExamenMenuItem1);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistiques");

        jMenuItem1.setText("Nombre d'etudiants inscrits par examen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem1);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InscriptionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscriptionMenuItemActionPerformed
        InscriptionExamenForm sf = new InscriptionExamenForm();
        desktopPane.add(sf);
        sf.setVisible(true);
    }//GEN-LAST:event_InscriptionMenuItemActionPerformed

    private void etudiantMenuEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantMenuEtudiantActionPerformed
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_etudiantMenuEtudiantActionPerformed

    private void ExamenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamenMenuItemActionPerformed
        ExamenForm exf = new ExamenForm();
        desktopPane.add(exf);
        exf.setVisible(true);
    }//GEN-LAST:event_ExamenMenuItemActionPerformed

    private void ExamenParMatiereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamenParMatiereMenuItemActionPerformed
        ExamenParMatiereForm epm;
        epm = new ExamenParMatiereForm();
        desktopPane.add(epm);
        epm.setVisible(true);
    }//GEN-LAST:event_ExamenParMatiereMenuItemActionPerformed

    private void EtudiantParExamenMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantParExamenMenuItem1ActionPerformed

        EtudiantParExamenForm epe;
        epe = new EtudiantParExamenForm();
        desktopPane.add(epe);
        epe.setVisible(true);

    }//GEN-LAST:event_EtudiantParExamenMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        BarchartForm barchartFrame = new BarchartForm();
        desktopPane.add(barchartFrame);
        barchartFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EtudiantParExamenMenuItem1;
    private javax.swing.JMenuItem ExamenMenuItem;
    private javax.swing.JMenuItem ExamenParMatiereMenuItem;
    private javax.swing.JMenuItem InscriptionMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem etudiantMenuEtudiant;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
